[package]
name = "counter"
version = "0.1.0"
edition = "2021"

[lib]
name = "counter"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
anchor-lang = "0.30.1"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = "s"
